// Level JSON to be read by the level builder.
var LEVELS = [
	{
		"name": "Main Menu",
		"width": 60,
		"height": 16,
		"bgColor": "lightgray",
		"bgImage": "bgs/title.png",
		"visRadiusColor": "darkgray",
		"playerStart": {
			"x": 4,
			"y": 10
		},
		"objects": [
			{
				"type": "platform",
				"x": 0,
				"y": 12,
				"width": 80,
				"height": 4,
				"color": "darkgray"
			}, {
				"type": "platform",
				"x": 25,
				"y": 9,
				"width": 3,
				"height": 1,
				"color": "darkgray"
			}, {
				"type": "door",
				"x": 26,
				"y": 7,
				"levelNum": 1
			}, {
				"type": "platform",
				"x": 30,
				"y": 9,
				"width": 3,
				"height": 1,
				"color": "darkgray"
			}, {
				"type": "door",
				"x": 31,
				"y": 7,
				"levelNum": 2
			}, {
				"type": "platform",
				"x": 35,
				"y": 9,
				"width": 3,
				"height": 1,
				"color": "darkgray"
			}, {
				"type": "door",
				"x": 36,
				"y": 7,
				"levelNum": 3
			}, {
				"type": "platform",
				"x": 40,
				"y": 9,
				"width": 3,
				"height": 1,
				"color": "darkgray"
			}, {
				"type": "door",
				"x": 41,
				"y": 7,
				"levelNum": 4
			}, {
				"type": "platform",
				"x": 45,
				"y": 9,
				"width": 3,
				"height": 1,
				"color": "darkgray"
			}, {
				"type": "door",
				"x": 46,
				"y": 7,
				"levelNum": 5
			}
		]
	}, {
		"name": "Level 1: The Startening",
		"width": 43,
		"height": 16,
		"bgColor": "lightgray",
		"visRadiusColor": "darkgray",
		"playerStart": {
			"x": 5,
			"y": 10
		},
		"objects": [
			{
				"type": "platform",
				"x": 0,
				"y": 13,
				"width": 19,
				"height": 3,
				"color": "darkgray"
			}, {
				"type": "platform",
				"x": 13,
				"y": 13,
				"width": 6,
				"height": 1,
				"color": "darkgray"
			}, {
				"type": "platform",
				"x": 14,
				"y": 12,
				"width": 5,
				"height": 1,
				"color": "darkgray"
			}, {
				"type": "platform",
				"x": 15,
				"y": 11,
				"width": 4,
				"height": 1,
				"color": "darkgray"
			}, {
				"type": "platform",
				"x": 16,
				"y": 10,
				"width": 3,
				"height": 1,
				"color": "darkgray"
			}, {
				"type": "platform",
				"x": 19,
				"y": 10,
				"width": 1,
				"height": 6,
				"color": "darkgray"
			}, {
				"type": "platform",
				"x": 23,
				"y": 10,
				"width": 20,
				"height": 6,
				"color": "darkgray"
			}, {
				"type": "platform",
				"x": 33,
				"y": 9,
				"width": 10,
				"height": 1,
				"color": "darkgray"
			}, {
				"type": "platform",
				"x": 34,
				"y": 8,
				"width": 9,
				"height": 1,
				"color": "darkgray"
			}, {
				"type": "platform",
				"x": 35,
				"y": 7,
				"width": 8,
				"height": 1,
				"color": "darkgray"
			}, {
				"type": "platform",
				"x": 36,
				"y": 6,
				"width": 7,
				"height": 1,
				"color": "darkgray"
			}, {
				"type": "platform",
				"x": 37,
				"y": 7,
				"width": 6,
				"height": 1,
				"color": "darkgray"
			}, {
				"type": "platform",
				"x": 38,
				"y": 6,
				"width": 5,
				"height": 1,
				"color": "darkgray"
			}, {
				"type": "bigPart",
				"x": 41,
				"y": 4
			}
		]
	}, {
		"name": "Level 2: Chromacide",
		"width": 70,
		"height": 20,
		"bgColor": "#fbf236",
		"bgImage": "bgs/bg2.png",
		"visRadiusColor": "#ff20e0",
		"playerStart": {
			"x": 2,
			"y": 8
		},
		"objects": [
			{
				"type": "platform",
				"x": 0,
				"y": 16,
				"width": 32,
				"height": 4,
				"color": "#fbf236"
			}, {
				"type": "platform",
				"x": 0,
				"y": 0,
				"width": 1,
				"height": 16,
				"color": "#fbf236"
			}, {
				"type": "platform",
				"x": 20,
				"y": 8,
				"width": 4,
				"height": 1,
				"color": "#fbf236"
			}, {
				"type": "platform",
				"x": 22,
				"y": 12,
				"width": 10,
				"height": 4,
				"color": "#fbf236"
			}, {
				"type": "platform",
				"x": 27,
				"y": 6,
				"width": 5,
				"height": 10,
				"color": "#fbf236"
			}, {
				"type": "platform",
				"x": 35,
				"y": 12,
				"width": 30,
				"height": 4,
				"color": "#fbf236"
			}, {
				"type": "platform",
				"x": 40,
				"y": 8,
				"width": 30,
				"height": 4,
				"color": "#fbf236"
			}, {
				"type": "platform",
				"x": 1,
				"y": 5,
				"width": 16,
				"height": 1,
				"color": "#fbf236"
			}, {
				"type": "bolt",
				"x": 2,
				"y": 1,
				"width": 2,
				"height": 2
			}, {
				"type": "bolt",
				"x": 30,
				"y": 1,
				"width": 2,
				"height": 2
			}, {
				"type": "bigPart",
				"x": 50,
				"y": 6,
				"width": 2,
				"height": 4
			}
		]
	}, {
		"name": "Level 3: Thread The Needle",
		"width": 40,
		"height": 20,
		"bgColor": "#5b6ee1",
		"bgImage": "bgs/bg3.png",
		"visRadiusColor": "red",
		"playerStart": {
			"x": 2,
			"y": 16
		},
		"objects": [
			{
				"type": "platform",
				"x": 0,
				"y": 0,
				"width": 1,
				"height": 18,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 0,
				"y": 18,
				"width": 21,
				"height": 3,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 1,
				"y": 15,
				"width": 3,
				"height": 1,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 1,
				"y": 13,
				"width": 2,
				"height": 1,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 1,
				"y": 11,
				"width": 1,
				"height": 1,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 3,
				"y": 9,
				"width": 1,
				"height": 1,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 1,
				"y": 6,
				"width": 1,
				"height": 1,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 2,
				"y": 3,
				"width": 3,
				"height": 1,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 5,
				"y": 11,
				"width": 1,
				"height": 7,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 5,
				"y": 0,
				"width": 1,
				"height": 8,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 5,
				"y": 11,
				"width": 6,
				"height": 1,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 11,
				"y": 9,
				"width": 1,
				"height": 3,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 9,
				"y": 15,
				"width": 2,
				"height": 1,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 9,
				"y": 15,
				"width": 1,
				"height": 3,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 13,
				"y": 15,
				"width": 1,
				"height": 1,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 14,
				"y": 14,
				"width": 3,
				"height": 1,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 14,
				"y": 9,
				"width": 1,
				"height": 1,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 16,
				"y": 11,
				"width": 1,
				"height": 1,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 17,
				"y": 7,
				"width": 1,
				"height": 11,
				"color": "#5b6ee1"
			}, {
				"type": "platform",
				"x": 20,
				"y": 0,
				"width": 1,
				"height": 20,
				"color": "#5b6ee1"
			}, { 
				"type": "bolt",
				"x": 3,
				"y": 2,
				"height": 2,
				"width": 2
			}, {
				"type": "bolt",
				"x": 6,
				"y": 15,
				"width": 2,
				"height": 4
			}, { // bigOne eventually
				"type": "bigPart",
				"x": 19,
				"y": 17,
				"width": 2,
				"height": 4
			}
		]
	}, {
		"name": "Level 4: Mad hops",
		"width": 50,
		"height": 25,
		"bgColor": "#76428a",
		"bgImage": "bgs/bg4.png",
		"visRadiusColor": "blue",
		"playerStart": {
			"x": 3,
			"y": 15
		},
		"objects": [
			{
				"type": "platform",
				"x": 0,
				"y": 0,
				"width": 1,
				"height": 20,
				"color": "#76428a"
			}, {
				"type": "platform",
				"x": 0,
				"y": 20,
				"width": 15,
				"height": 1,
				"color": "#5fcde4"
			}, {
				"type": "platform",
				"x": 20,
				"y": 20,
				"width": 15,
				"height": 1,
				"color": "#5fcde4"
			}, {
				"type": "platform",
				"x": 36,
				"y": 18,
				"width": 3,
				"height": 1,
				"color": "#3f3f74"
			}, {
				"type": "platform",
				"x": 30,
				"y": 15,
				"width": 3,
				"height": 1,
				"color": "#3f3f74"
			},  {
				"type": "platform",
				"x": 24,
				"y": 12,
				"width": 3,
				"height": 1,
				"color": "#76428a"
			},  {
				"type": "platform",
				"x": 15,
				"y": 9,
				"width": 6,
				"height": 1,
				"color": "#76428a"
			}, { // door eventually
				"type": "bigPart",
				"x": 5,
				"y": 5,
				"width": 2,
				"height": 4
			}
		]
	}, {
		"name": "Level 5: Choices",
		"width": 60,
		"height": 60,
		"bgColor": "black",
		"bgImage": "bgs/bg5.png",
		"playerStart": {
			"x": 2,
			"y": 43
		},
		"objects": [
			{
				"type": "platform",
				"x": 0,
				"y": 0,
				"width": 1,
				"height": 48,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 0,
				"y": 48,
				"width": 3,
				"height": 1,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 3,
				"y": 45,
				"width": 1,
				"height": 3,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 3,
				"y": 45,
				"width": 45,
				"height": 1,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 48,
				"y": 0,
				"width": 1,
				"height": 45,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 3,
				"y": 36,
				"width": 1,
				"height": 5,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 3,
				"y": 41,
				"width": 16,
				"height": 1,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 22,
				"y": 41,
				"width": 2,
				"height": 1,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 23,
				"y": 36,
				"width": 1,
				"height": 6,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 6,
				"y": 37,
				"width": 18,
				"height": 1,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 3,
				"y": 33,
				"width": 18,
				"height": 1,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 24,
				"y": 32,
				"width": 18,
				"height": 1,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 26,
				"y": 36,
				"width": 8,
				"height": 4,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 0,
				"y": 29,
				"width": 6,
				"height": 1,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 10,
				"y": 29,
				"width": 14,
				"height": 1,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 44,
				"y": 29,
				"width": 4,
				"height": 2,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 40,
				"y": 25,
				"width": 2,
				"height": 2,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 36,
				"y": 21,
				"width": 2,
				"height": 2,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 40,
				"y": 18,
				"width": 2,
				"height": 2,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 36,
				"y": 14,
				"width": 2,
				"height": 2,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 0,
				"y": 14,
				"width": 32,
				"height": 2,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 36,
				"y": 9,
				"width": 13,
				"height": 1,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 0,
				"y": 11,
				"width": 6,
				"height": 1,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 6,
				"y": 8,
				"width": 13,
				"height": 1,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 28,
				"y": 5,
				"width": 4,
				"height": 1,
				"color": "#ffff00"
			}, {
				"type": "platform",
				"x": 20,
				"y": 6,
				"width": 4,
				"height": 1,
				"color": "#ffff00"
			}, { // door eventually
				"type": "bigPart",
				"x": 45,
				"y": 5,
				"width": 2,
				"height": 4
			}
		]
	}
];
